_wandb:
    value:
        cli_version: 0.23.0
        e:
            0m72u3ao7tweobjwp0lyeb9r3ivease7:
                codePath: c:\cifar-week3\notebooks\02_from_scratch_training.ipynb
                codePathLocal: 02_from_scratch_training.ipynb
                cpu_count: 8
                cpu_count_logical: 16
                cudaVersion: "12.4"
                disk:
                    /:
                        total: "476690321408"
                        used: "358137376768"
                email: usansrita@gmail.com
                executable: c:\cifar-week3\venv\Scripts\python.exe
                gpu: NVIDIA GeForce RTX 3060 Laptop GPU
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 3840
                      memoryTotal: "6442450944"
                      name: NVIDIA GeForce RTX 3060 Laptop GPU
                      uuid: GPU-68085c59-512c-06bb-e133-c2b6ab672a12
                host: Sans
                memory:
                    total: "16542732288"
                os: Windows-11-10.0.26200-SP0
                program: c:\cifar-week3\notebooks\02_from_scratch_training.ipynb
                python: CPython 3.13.9
                root: c:\cifar-week3\notebooks
                startedAt: "2025-12-04T09:32:10.223359Z"
                writerId: 0m72u3ao7tweobjwp0lyeb9r3ivease7
        m: []
        python_version: 3.13.9
        t:
            "1":
                - 1
                - 41
            "2":
                - 1
                - 41
            "3":
                - 2
                - 13
                - 16
            "4": 3.13.9
            "5": 0.23.0
            "8":
                - 1
                - 3
            "12": 0.23.0
            "13": windows-amd64
amp:
    value: true
augmentation:
    value: basic + RandAugment
batch_size:
    value: 128
epochs:
    value: 50
lr_max:
    value: 0.1
model:
    value: CNN9 (from scratch)
optimizer:
    value: SGD + OneCycleLR
weight_decay:
    value: 0.0005
