_wandb:
    value:
        cli_version: 0.23.0
        e:
            u47g1xblk6or459cnkf62js5h3danx1n:
                codePath: c:\cifar-week3\notebooks\04_.ipynb
                codePathLocal: 04_.ipynb
                cpu_count: 8
                cpu_count_logical: 16
                cudaVersion: "12.4"
                disk:
                    /:
                        total: "476690321408"
                        used: "316685193216"
                email: usansrita@gmail.com
                executable: c:\cifar-week3\venv\Scripts\python.exe
                gpu: NVIDIA GeForce RTX 3060 Laptop GPU
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 3840
                      memoryTotal: "6442450944"
                      name: NVIDIA GeForce RTX 3060 Laptop GPU
                      uuid: GPU-68085c59-512c-06bb-e133-c2b6ab672a12
                host: Sans
                memory:
                    total: "16542732288"
                os: Windows-11-10.0.26200-SP0
                program: c:\cifar-week3\notebooks\04_.ipynb
                python: CPython 3.13.9
                root: c:\cifar-week3\notebooks
                startedAt: "2025-12-08T06:21:47.542057Z"
                writerId: u47g1xblk6or459cnkf62js5h3danx1n
        m: []
        python_version: 3.13.9
        t:
            "1":
                - 1
                - 5
                - 41
                - 49
                - 53
                - 63
            "2":
                - 1
                - 5
                - 41
                - 49
                - 53
                - 63
            "3":
                - 2
                - 13
                - 16
            "4": 3.13.9
            "5": 0.23.0
            "8":
                - 1
                - 3
            "12": 0.23.0
            "13": windows-amd64
artifacts_dir:
    value: artifacts
batch_size:
    value: 64
data_root:
    value: ./data
device:
    value: cuda
ece_bins:
    value: 15
model:
    value: ResNet18 (fine-tuned)
model_path:
    value: C:/cifar-week3/artifacts/randaug_final.pth
noise_std:
    value: 0.1
num_classes:
    value: 10
num_gradcam:
    value: 20
num_misclassified:
    value: 20
task:
    value: Diagnostics + Attribution + Calibration
