_wandb:
    value:
        cli_version: 0.23.0
        e:
            hod4ewpic2zen5xg4un9j1jjeqmvqgof:
                codePath: c:\cifar-week3\notebooks\03_transfer_learning.ipynb
                codePathLocal: 03_transfer_learning.ipynb
                cpu_count: 8
                cpu_count_logical: 16
                cudaVersion: "12.4"
                disk:
                    /:
                        total: "476690321408"
                        used: "349323948032"
                email: usansrita@gmail.com
                executable: c:\cifar-week3\venv\Scripts\python.exe
                gpu: NVIDIA GeForce RTX 3060 Laptop GPU
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 3840
                      memoryTotal: "6442450944"
                      name: NVIDIA GeForce RTX 3060 Laptop GPU
                      uuid: GPU-68085c59-512c-06bb-e133-c2b6ab672a12
                host: Sans
                memory:
                    total: "16542732288"
                os: Windows-11-10.0.26200-SP0
                program: c:\cifar-week3\notebooks\03_transfer_learning.ipynb
                python: CPython 3.13.9
                root: c:\cifar-week3\notebooks
                startedAt: "2025-12-04T10:36:46.766791Z"
                writerId: hod4ewpic2zen5xg4un9j1jjeqmvqgof
        m: []
        python_version: 3.13.9
        t:
            "1":
                - 1
                - 41
                - 49
                - 63
            "2":
                - 1
                - 41
                - 49
                - 63
            "3":
                - 2
                - 13
                - 16
            "4": 3.13.9
            "5": 0.23.0
            "8":
                - 1
                - 3
            "12": 0.23.0
            "13": windows-amd64
epochs:
    value: 25
model:
    value: resnet18
unfreeze:
    value:
        - layer1
        - layer2
        - layer3
        - layer4
